disasm64.exe t1.com > test-result.txt
disasm64.exe t2.com >> test-result.txt
disasm64.exe t3-add.com >> test-result.txt
disasm64.exe t4-adc.com >> test-result.txt
disasm64.exe t5-cmp.com >> test-result.txt
disasm64.exe t5-sub.com >> test-result.txt
disasm64.exe t6-sbb.com >> test-result.txt
disasm64.exe t8-mdiv.com >> test-result.txt
disasm64.exe t9-oar.com >> test-result.txt
disasm64.exe t10-log.com >> test-result.txt
disasm64.exe t11-strc.com >> test-result.txt
disasm64.exe T12-JMPS.com >> test-result.txt
